interface IENV {
  DB_HOST: string;
  DB_DATABASE: string;
  DB_PORT: number;
  DB_TYPE: 'mysql' | 'mariadb';
  DB_USERNAME: string;
  DB_PASSWORD: string;
  REDIS_PORT: number;
  REDIS_HOST: string;
  GO_RUSH_ADDRESS: string;
  GO_RUSH_IOS_CLIP_TOPIC: string;
  GO_RUSH_IOS_TOPIC: string;
  GO_RUSH_IOS_PORT: number;
  GO_RUSH_IOS_CLIP_PORT: number;
  APP_DEBUG: boolean;
  MAX_PUSH_EVERY_USER_PER_MINUTE: number;
  MAX_PUSH_KEY_PER_TIME: number;
  MAX_EVERY_API_LIMIT_PER_MINUTE: number;
  GITHUB_CLIENT_ID: string;
  GITHUB_CLIENT_SECRET: string;
}

const {
  DB_HOST = '127.0.0.1',
  DB_DATABASE = 'pushdeer',
  DB_PORT = 3306,
  DB_USERNAME = 'root',
  DB_PASSWORD = 'theVeryp@ssw0rd',
  REDIS_PORT = 6379,
  REDIS_HOST = '127.0.0.1',
  DB_TYPE = 'mariadb',
  GO_RUSH_ADDRESS = '127.0.0.1',
  GO_RUSH_IOS_CLIP_TOPIC = 'com.pushdeer.self.ios.Clip',
  GO_RUSH_IOS_TOPIC = 'com.pushdeer.self.ios',
  GO_RUSH_IOS_PORT = 18888,
  GO_RUSH_IOS_CLIP_PORT = 18080,
  APP_DEBUG = false,
  MAX_PUSH_EVERY_USER_PER_MINUTE = 120,
  MAX_PUSH_KEY_PER_TIME = 100,
  MAX_EVERY_API_LIMIT_PER_MINUTE = 60,
  GITHUB_CLIENT_ID = '8c6833674f0e10827f8e',
  GITHUB_CLIENT_SECRET = '0b7eb70c67344399f6bb3aa6220a98a327148f23',
} = process.env as unknown as IENV;

const HTTP_PORT = 8800;

export {
  DB_HOST,
  DB_DATABASE,
  DB_PORT,
  DB_USERNAME,
  DB_PASSWORD,
  DB_TYPE,
  HTTP_PORT,
  REDIS_PORT,
  REDIS_HOST,
  GO_RUSH_ADDRESS,
  GO_RUSH_IOS_CLIP_TOPIC,
  GO_RUSH_IOS_TOPIC,
  GO_RUSH_IOS_PORT,
  GO_RUSH_IOS_CLIP_PORT,
  APP_DEBUG,
  MAX_PUSH_EVERY_USER_PER_MINUTE,
  MAX_PUSH_KEY_PER_TIME,
  MAX_EVERY_API_LIMIT_PER_MINUTE,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
};
